### ISSUE TITLE
Move to ESM

### ISSUE THREAD

**Issue by wgyt** [1hostjs/hosting#59]
> @GrahamSH-LLK We can't merge this because we would need to import chalk using ESM which isn't what we use :|
> See https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

I've been meaning to 100% move to ESM. It's so much cleaner and nicer.

_Originally posted by @GrahamSH-LLK in https://github.com/1hostjs/hosting/issues/58#issuecomment-821125874_

**Comment by wgyt** [comment]
Once we do this we can merge #58

**Comment by wgyt** [comment]
This is almost done in #62 but I need to fix some issues with serve.mjs

**Comment by wgyt** [comment]
The error is:
```
gitpod /workspace/hosting/tests/posix $ 1host

   ╭────────────────────────╮
   │                        │
   │   ✔ 1host.js Success   │
   │                        │
   │   Starting...          │
   │                        │
   ╰────────────────────────╯


Serving
[
  [
    { module: [Function (anonymous)], data: [Object] },
    errorHandler: { module: [AsyncFunction (anonymous)], data: [Object] }
  ],
  3000
]
file:///workspace/hosting/src/serve.mjs:43
          modules.errorHandler.module(req, res, 500);
                  ^

TypeError: Cannot read property 'errorHandler' of undefined
    at Server.<anonymous> (file:///workspace/hosting/src/serve.mjs:43:19)
    at Server.emit (events.js:315:20)
    at parserOnIncoming (_http_server.js:874:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
```
