### ISSUE TITLE
res.write sends undefined

### ISSUE THREAD

**Issue by wgyt** [1hostjs/hosting#97]
even tho there is content

**Comment by wgyt** [comment]
this seems like a @1hostjs/errors issue, here is the stack trace:
```
(node:480) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer or Uint8Array. Received undefined
    at write_ (_http_outgoing.js:696:11)
    at ServerResponse.write (_http_outgoing.js:661:15)
    at /home/runner/scratchauth/scratchCommentAuth/node_modules/@1hostjs/errors/index.js:29:11
    at tryHandleCache (/home/runner/scratchauth/scratchCommentAuth/node_modules/@1hostjs/errors/node_modules/ejs/lib/ejs.js:275:14)
    at Object.exports.renderFile (/home/runner/scratchauth/scratchCommentAuth/node_modules/@1hostjs/errors/node_modules/ejs/lib/ejs.js:489:10)
    at Object.module.exports [as module] (/home/runner/scratchauth/scratchCommentAuth/node_modules/@1hostjs/errors/index.js:17:7)
    at serverfunction (file:///home/runner/.npm/_npx/480/lib/node_modules/@1hostjs/hosting/src/serve.js:59:28)
    at Server.<anonymous> (file:///home/runner/.npm/_npx/480/lib/node_modules/@1hostjs/hosting/src/serve.js:72:9)
    at Server.emit (events.js:315:20)
    at parserOnIncoming (_http_server.js:874:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:480) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:480) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
